name: module_codegen_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  analyzer: ^5.13.0
  build: ^2.3.1
  build_config: ^1.1.1
  source_gen: ^1.3.2
  module_codegen:
    path: '../module_codegen'

dev_dependencies:
  build_runner: ^2.3.3
  lints: ^2.0.0
  test: ^1.21.0
  module_analyzer:
    path: '../module_analyzer'
