name: module_business
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  get_it: ^7.6.0
  injectable: ^2.1.2
  module_model:
    path: '../module_model'
  module_data:
    path: '../module_data'

#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  injectable_generator: ^2.1.6
  build_runner: ^2.3.3
  module_analyzer:
    path: '../module_analyzer'
