name: module_analyzer
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dart_code_metrics: ^5.7.5
  pedantic:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

